### ISSUE TITLE
Example Run creates no data

### ISSUE THREAD

**Issue by irishman34** [beliveau-lab/PaintSHOP_pipeline#20]
After creating and activating the environment, I get the following output on my command line when running the example:
```
$ ./run_pipeline.sh
./run_pipeline.sh: line 8: activate: No such file or directory
Building DAG of jobs...
Traceback (most recent call last):
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/__init__.py", line 626, in snakemake
    success = workflow.execute(
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 836, in execute
    dag.create_conda_envs(
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 280, in create_conda_envs
    env.create(dryrun)
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 247, in create
    conda = Conda(self._container_img)
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 381, in __new__
    inst.__init__(container_img=container_img)
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 394, in __init__
    self._check()
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 448, in _check
    if StrictVersion(version) < StrictVersion("4.2"):
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/home/sam/miniforge3/envs/paintshop_snakemake/lib/python3.8/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number 'while'
Exporting pipeline DAG to svg and pdf...
Building DAG of jobs...
Generating pipeline HTML report...
Building DAG of jobs...
Creating report...
Missing metadata for file pipeline_output/DONE.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/03_output_files/04_zip_archives/Example1_all_newBalance.zip. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/03_output_files/04_zip_archives/Example1_refseq_newBalance.zip. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/03_output_files/04_zip_archives/Example1_iso_newBalance.zip. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/03_output_files/01_dna_probes/Example1_all_newBalance.tsv. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/03_output_files/02_rna_probes_all/Example1_refseq_newBalance.tsv. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/03_output_files/03_rna_probes_iso/Example1_iso_newBalance.tsv. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/03_chrom_fastas. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/05_annotation_files/Example1.bed. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/02_intermediate_files/01_chrom_gtf_dataframes. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/05_annotation_files/Example1_iso_flat.bed. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/01_chrom_names/chrom_names.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/01_chrom_names/removed_unk.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/01_chrom_names/removed_excl.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/01_chrom_names/removed_rand.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/01_chrom_names/removed_alt.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/01_chrom_names/removed_hap.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/01_chrom_names/removed_fix.txt. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Missing metadata for file pipeline_output/01_reference_files/02_multi_fasta/Example1.fa. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Downloading resources and rendering HTML.
Report created: pipeline_output/report.html.
[pipeline.pdf](https://github.com/user-attachments/files/16956587/pipeline.pdf)

DONE!
```

I'm not familiar with Snakemake and I'm unsure what I have done wrong. It seems to be unable to create any of the output data. I've attached the generated .pdf as well. Are there other dependencies that I am missing?

-Thanks
[pipeline.pdf](https://github.com/user-attachments/files/16956602/pipeline.pdf)

**Comment by irishman34** [comment]
Restarting my computer fixed this

**Comment by hackkr** [comment]
Hi,

I'm running into a similar error after installing on a cluster, and opening new terminal windows has not resolved my issue. I am using a local version of miniforge, since I cannot modify the cluster's miniconda which lacks mamba. Any tips on troubleshooting?

```
./run_pipeline.sh: line 8: activate: No such file or directory
Building DAG of jobs...
Creating conda environment ../workflow/envs/environment.yml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /fs/ess/PAS2884/paintshop/PaintSHOP_pipeline/workflow/envs/environment.yml:
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.

  File "/users/PAS2884/hackkr/miniforge3/envs/paintshop_snakemake/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 350, in create
```
